apiVersion: v1
kind: Service
metadata:
  name: brain-tasks-service
spec:
  type: LoadBalancer
  selector:
    app: brain-tasks-app
  ports:
    - port: 80         # ELB will listen on 80
      targetPort: 3000 # Forward traffic to container's 3000